# Generated by Django 4.2.21 on 2025-05-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
