# Generated by Django 4.2.21 on 2025-05-17 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('description_long', models.TextField()),
                ('link_be', models.TextField(blank=True, null=True)),
                ('link_fe', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='api.project')),
            ],
        ),
    ]
