# Generated by Django 4.2.21 on 2025-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='link_youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
