# Generated by Django 4.2.21 on 2025-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectdetail_link_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_vn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
