# Generated by Django 4.2.21 on 2025-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_description_vn'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='description_long_vn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
