# Generated by Django 4.2.21 on 2025-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectdetail_description_long_vn'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='date_vn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
